### ISSUE TITLE
自动化录入建议

### ISSUE THREAD

**Issue by jxtxzzw** [ECNUCSE/ECNU_ITers#6]
1.  建议列表增加字段：入学年，学院，并以此排序
2.  提供输入页，提交后通过 bot 自动合并入主页面，避免 fork 和人工解决冲突

**Comment by LEODPEN** [comment]
长老已经是owner啦，可以操作一下呀

**Comment by LEODPEN** [comment]
初步设想是等第一批member先基本稳定再操作

**Comment by 2014CAIS01** [comment]
建议录入信息的 merge 使用 rebase 或 squash 的方式合并。

**Comment by jxtxzzw** [comment]
> 建议手动录入信息的 merge 使用 rebase 或 squash 的方式合并。

蔡队也是 owner 哦，可以设置一下。我已经在 setting 中禁用了默认 merge，现在第一顺位应该是 squash merge。
